name: multi-arch docker build using qemu

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: set up qemu for linux/arm64
        uses: docker/setup-qemu-action@v1

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build multi-arch image and push to docker hub
        run: |
          docker buildx build --push \
            --tag rsubr/php-ubuntu:latest \
            --tag rsubr/php-ubuntu:focal  \
            --tag rsubr/php-ubuntu:20.04  \
            --platform linux/amd64,linux/arm64 .